### ISSUE TITLE
Appveyor py27: UnicodeDecodeError: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by shadowwalkersb** [conda-forge/libgit2-feedstock#12]
I am seeing failures for `CONDA_PY=27` on Appveyor. Currently, I have two PRs that fail due to this, #10 and #11 . Not sure if it is package specific.

```
Traceback (most recent call last):
  File "C:\Miniconda\Scripts\conda-build-script.py", line 5, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "C:\Miniconda\lib\site-packages\conda_build\cli\main_build.py", line 322, in main
    execute(sys.argv[1:])
  File "C:\Miniconda\lib\site-packages\conda_build\cli\main_build.py", line 313, in execute
    noverify=args.no_verify)
  File "C:\Miniconda\lib\site-packages\conda_build\api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 1484, in build_tree
    config=config)
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 983, in build
    config=config)
  File "C:\Miniconda\lib\site-packages\conda_build\render.py", line 86, in parse_or_try_download
    source.provide(metadata, config=config)
  File "C:\Miniconda\lib\site-packages\conda_build\source.py", line 505, in provide
    unpack(metadata, config=config)
  File "C:\Miniconda\lib\site-packages\conda_build\source.py", line 90, in unpack
    tar_xf(src_path, config.work_dir)
  File "C:\Miniconda\lib\site-packages\conda_build\utils.py", line 314, in tar_xf
    t.extractall(path=dir_path)
  File "C:\Miniconda\lib\tarfile.py", line 2079, in extractall
    self.extract(tarinfo, path)
  File "C:\Miniconda\lib\tarfile.py", line 2116, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "C:\Miniconda\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 38: ordinal not in range(128)

```

**Comment by jakirkham** [comment]
Do they persist on restart?

**Comment by shadowwalkersb** [comment]
I have 3 restarts of one of the PRa. Just restarted the other one. There are a couple 'can't find conda' (which I know has been reported) errors, but all others are the same error as in OP.

**Comment by jakirkham** [comment]
Really? Do you have references for those builds?

**Comment by shadowwalkersb** [comment]
If you follow builds in the PRs.

**Comment by shadowwalkersb** [comment]
https://ci.appveyor.com/project/conda-forge/libgit2-feedstock/history

**Comment by jakirkham** [comment]
Could you please link a specific example of 'can't find conda'? If it is older than 2 days, it is not relevant FYI as that issue was fixed 2 days ago.

**Comment by shadowwalkersb** [comment]
https://ci.appveyor.com/project/conda-forge/libgit2-feedstock/build/1.0.41/job/3fswypgm0sp4gwy2
https://ci.appveyor.com/project/conda-forge/libgit2-feedstock/build/1.0.42/job/3d8ndw5nty16uivv

**Comment by jakirkham** [comment]
So those appear to be 2 days old though. Did the same issue crop up yesterday or today?

**Comment by shadowwalkersb** [comment]
Nope. I was aware of the issue and that it was fixed, so didn't bother reporting. Any ideas about the problem related to `UnicodeDecodeError`?
